# This contains params to be used by the stages to train or predict
prepare:
  split: 0.3
  seed: 2022
  tag: <python>

featurize:
  max_features: 3000
  n_grams: 3

train:
  seed: 2022
  n_est: 100
  min_split: 16
  n_jobs: 2
